arch:
  - amd64
  - ppc64le

language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - master

install:
  - go get -t ./...

before_script: ./check_third_party.sh
script: go test -short -v ./...

sudo: false
