language: go

go:
  - 1.2
  - 1.3
  - 1.4

install:
  - go get github.com/smartystreets/assertions
  - go get golang.org/x/tools/cover
  - go get github.com/jtolds/gls

script: go test -short -v ./...

sudo: false
